WebTraining/Controllers/MeasurementsController/SingleMeasurementsController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebTraining.Core.DTO.MeasurementsDTO;
using WebTraining.Core.Interfaces.IMeasurements;
using WebTraining.Core.Services.MeasurementsService;
using WebTraining.DB.Models;
using WebTraining.Models.Measurements;

namespace WebTraining.Controllers.MeasurementsController
{
    public class SingleMeasurementsController : Controller
    {
        private readonly ISingleMeasurementstService singleservice;
        readonly UserManager<User> userManager;

        public SingleMeasurementsController(ISingleMeasurementstService singleservice, UserManager<User> userManager)
        {
            this.singleservice = singleservice;
            this.userManager= userManager;
        }

        public async Task<IActionResult> ButtocksViewMeasurements(string type = "Ягодицы")
        {
            User user = await GetUser();
            ButtocksMeasViewModel model = new ButtocksMeasViewModel()
            {
                Measurements = singleservice.GetNeedMeasurements(user, singleservice.GetTypeOfMuscle(type).ID).ToList()
            };
            return View(model);
        }

        public async Task<IActionResult> WaistViewMeasurements(string type = "Талия")
        {
            User user = await GetUser();
            WaistMeasViewModel model = new WaistMeasViewModel()
            {
                Measurements = singleservice.GetNeedMeasurements(user, singleservice.GetTypeOfMuscle(type).ID).ToList()
            };
            return View(model);
        }

        public async Task<IActionResult> HeightViewMeasurements(string type = "Рост")
        {
            User user = await GetUser();
            HeightMeasViewModel model = new HeightMeasViewModel()
            {
                Measurements = singleservice.GetNeedMeasurements(user, singleservice.GetTypeOfMuscle(type).ID).ToList()
            };
            return View(model);
        }

        public async Task<IActionResult> WeightViewMeasurements(string type = "Вес")
        {
            User user = await GetUser();
            WeightMeasViewModel model = new WeightMeasViewModel()
            {
                Measurements = singleservice.GetNeedMeasurements(user, singleservice.GetTypeOfMuscle(type).ID).ToList()
            };
            return View(model);
        }

        public async Task<IActionResult> BreastViewMeasurements(string type = "Грудь")
        {
            User user = await GetUser();
            BreastMeasViewModel model = new BreastMeasViewModel()
            {
                Measurements = singleservice.GetNeedMeasurements(user, singleservice.GetTypeOfMuscle(type).ID).ToList()
            };
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Add(string id)
        {
            User user = await GetUser();
            AddSingleMeasViewModel meas = new AddSingleMeasViewModel
            {
                Measurementst = new SingleMeasurementstDTO()
                {
                    Date = DateTime.Now,
                    UserId = user.Id,
                    MuscleId = singleservice.GetTypeOfMuscle(id).ID
                }
            };
            return View(meas);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddSingleMeasViewModel meas)
        {
            User user = await GetUser();
            if (ModelState.IsValid)
            {
                singleservice.AddMeasurement(meas.Measurementst, user);
                return RedirectToAction("Index", "Account");
            }
            else
            {
                return View(meas);
            }
        }

        public IActionResult Delete(int id) 
        {
            singleservice.DeleteMeasurement(id);
            return RedirectToAction("Index", "Account");
        }

        [HttpGet]
        public IActionResult Edit(int id) 
        {
            SingleMeasurementstDTO meas = singleservice.GetMeasurement(id);
            if (meas != null)
            {
                return View(meas);
            }
            return RedirectToAction("Index", "Account");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(SingleMeasurementstDTO meas) 
        {
            User user = await GetUser();
            if (ModelState.IsValid)
            {
                singleservice.UpdateMeasurement(meas, user);
                return RedirectToAction("Index", "Account");
            }
            return View(meas);
        }

        private async Task<User> GetUser()
        {
            return await userManager.FindByNameAsync(User.Identity.Name);
        }
    }
}

WebTraining/Views/SingleMeasurements/Add.cshtml
@using WebTraining.Models.Measurements;
@model AddSingleMeasViewModel;

<h1>Добавить значение</h1>

<form asp-action="Add" method="post">
    <div class="div-crud-data">
        <label class="label-crud-data" asp-for="Measurementst.Value">Значение</label>
        <input class="input-crud-data-exercise" asp-for="Measurementst.Value" type="text" maxlength="6" />
        <span asp-validation-for="Measurementst.Value"></span>
    </div>
    <div hidden>
        <label asp-for="Measurementst.Date"></label>
        <input asp-for="Measurementst.Date" type="datetime" />
        <span asp-validation-for="Measurementst.Date"></span>
    </div>
    <div hidden>
        <label asp-for="Measurementst.UserId"></label>
        <input asp-for="Measurementst.UserId" />
        <span asp-validation-for="Measurementst.UserId"></span>
    </div>
    <div hidden>
        <label asp-for="Measurementst.MuscleId"></label>
        <input asp-for="Measurementst.MuscleId" />
        <span asp-validation-for="Measurementst.MuscleId"></span>
    </div>

    <div>
        <input class="btn-add" type="submit" value="Добавить" />
    </div>

</form>

WebTraining/Views/SingleMeasurements/BreastViewMeasurements.cshtml
@using WebTraining.Models.Measurements;
@model BreastMeasViewModel
@{
    ViewData["Title"] = "Значения";
}

<h1>Замеры груди</h1>

<table class="table">
    <thead>
        <tr>
            <th><a>Дата</a></th>
            <th><a>Значение</a></th>
            <th><a>Изменение</a></th>



        </tr>
    </thead>
    <tbody>
        @foreach (var meas in Model.Measurements.OrderBy(x => x.Date).Reverse())
        {
            <tr>
                <td>
                    @Html.DisplayFor(item => meas.Date)
                </td>
                <td align="center">
                    @Html.DisplayFor(item => meas.Value) см
                </td>
                <td align="center">
                    @if (meas.Change > 0)
                    {
                        <a>+</a>

                        @Html.DisplayFor(item => meas.Change)
                    }
                    else
                    {
                        @Html.DisplayFor(item => meas.Change)
                    }
                </td>
                @if (meas == Model.Measurements.OrderBy(x => x.Date).Reverse().First())
                {
                <td>
                    <form method="get" asp-action="Edit" asp-route-id="@meas.ID">
                        <button class="btn-crud-data">Изменить</button>
                    </form>
                </td>
                    <td>
                            <form method="get" asp-action="Delete" asp-route-id="@meas.ID">
                                <button class="btn-crud-data">Удалить</button>
                            </form>
                    </td>
                 }
            </tr>
        }
    </tbody>
</table>

<form method="get" asp-controller="SingleMeasurements" asp-action="Add" asp-route-id="@Model.Muscles">
    <button class="btn-crud-data" method="get" asp-controller="SingleMeasurements" asp-action="Add" asp-route-id="@Model.Muscles">Добавить</button>
</form>

WebTraining/Views/SingleMeasurements/ButtocksViewMeasurements.cshtml
@using WebTraining.Models.Measurements;
@model ButtocksMeasViewModel
@{
    ViewData["Title"] = "Значения";
}

<h1>Замеры ягодиц</h1>

<table class="table">
    <thead>
        <tr>
            <th><a>Дата</a></th>
            <th><a>Значение</a></th>
            <th><a>Изменение</a></th>



        </tr>
    </thead>
    <tbody>
        @foreach (var meas in Model.Measurements.OrderBy(x => x.Date).Reverse())
        {
            <tr>
                <td>
                    @Html.DisplayFor(item => meas.Date)
                </td>
                <td align="center">
                    @Html.DisplayFor(item => meas.Value) см
                </td>
                <td align="center">
                    @if (meas.Change > 0)
                    {
                        <a>+</a>

                        @Html.DisplayFor(item => meas.Change)
                    }
                    else
                    {
                        @Html.DisplayFor(item => meas.Change)
                    }
                </td>


                @if (meas == Model.Measurements.OrderBy(x => x.Date).Reverse().First())
                {
                    <td>
                        <form method="get" asp-action="Edit" asp-route-id="@meas.ID">
                            <button class="btn-crud-data">Изменить</button>
                        </form>
                    </td>
                    <td>
                        <form method="get" asp-action="Delete" asp-route-id="@meas.ID">
                            <button class="btn-crud-data">Удалить</button>
                        </form>
                    </td>
                }


            </tr>
        }
    </tbody>
</table>

<form method="get" asp-controller="SingleMeasurements" asp-action="Add" asp-route-id="@Model.Muscles">
    <button class="btn-crud-data" method="get" asp-controller="SingleMeasurements" asp-action="Add" asp-route-id="@Model.Muscles">Добавить</button>
</form>

WebTraining/Views/SingleMeasurements/Edit.cshtml
@model WebTraining.Core.DTO.MeasurementsDTO.SingleMeasurementstDTO

<h1>Редактировать измерения</h1>

<form method="post" asp-action="Edit">
    <div class="div-crud-data">
        <label class="label-crud-data" asp-for="Value">Значение</label>
        <input class="input-crud-data-exercise" asp-for="Value" type="text"/>
        <span asp-validation-for="Value"></span>
    </div>

    <div hidden>
        <label asp-for="Date"></label>
        <input asp-for="Date" type="datetime" />
        <span asp-validation-for="Date"></span>
    </div>
    <div hidden>
        <label asp-for="UserId"></label>
        <input asp-for="UserId" />
        <span asp-validation-for="UserId"></span>
    </div>
    <div hidden>
        <label asp-for="MuscleId"></label>
        <input asp-for="MuscleId" />
        <span asp-validation-for="MuscleId"></span>
    </div>
    <div>
        <input class="btn-add" type="submit" value="Изменить" />
    </div>
</form>

WebTraining/Views/SingleMeasurements/HeightViewMeasurements.cshtml
@using WebTraining.Models.Measurements;
@model HeightMeasViewModel
@{
    ViewData["Title"] = "Значения";
}

<h1>Замеры роста</h1>

<table class="table">
    <thead>
        <tr>
            <th><a>Дата</a></th>
            <th><a>Значение</a></th>
            <th><a>Изменение</a></th>



        </tr>
    </thead>
    <tbody>
        @foreach (var meas in Model.Measurements.OrderBy(x => x.Date).Reverse())
        {
                <tr>
                    <td>
                    @Html.DisplayFor(item => meas.Date)
                    </td>
                    <td align="center">
                    @Html.DisplayFor(item => meas.Value) см
                    </td>
                    <td align="center">
                    @if (meas.Change > 0)
                    {
                                <a>+</a>

                        @Html.DisplayFor(item => meas.Change)
                    }
                    else
                    {
                        @Html.DisplayFor(item => meas.Change)
                    }
                    </td>


                @if (meas == Model.Measurements.OrderBy(x => x.Date).Reverse().First())
                {
                    <td>
                        <form method="get" asp-action="Edit" asp-route-id="@meas.ID">
                            <button class="btn-crud-data">Изменить</button>
                        </form>
                    </td>
                    <td>
                        <form method="get" asp-action="Delete" asp-route-id="@meas.ID">
                            <button class="btn-crud-data">Удалить</button>
                        </form>
                    </td>
                }
                </tr>
        }
    </tbody>
</table>

<form method="get" asp-controller="SingleMeasurements" asp-action="Add" asp-route-id="@Model.Muscles">
    <button class="btn-crud-data" method="get" asp-controller="SingleMeasurements" asp-action="Add" asp-route-id="@Model.Muscles">Добавить</button>
</form>

WebTraining/Views/SingleMeasurements/WaistViewMeasurements.cshtml
@using WebTraining.Models.Measurements;
@model WaistMeasViewModel
@{
    ViewData["Title"] = "Значения";
}

<h1>Замеры талии</h1>

<table class="table">
    <thead>
        <tr>
            <th><a>Дата</a></th>
            <th><a>Значение</a></th>
            <th><a>Изменение</a></th>



        </tr>
    </thead>
    <tbody>
        @foreach (var meas in Model.Measurements.OrderBy(x => x.Date).Reverse())
        {
            <tr>
                <td>
                    @Html.DisplayFor(item => meas.Date)
                </td>
                <td align="center">
                    @Html.DisplayFor(item => meas.Value) см
                </td>
                <td align="center">
                    @if (meas.Change > 0)
                    {
                        <a>+</a>

                        @Html.DisplayFor(item => meas.Change)
                    }
                    else
                    {
                        @Html.DisplayFor(item => meas.Change)
                    }
                </td>


                @if (meas == Model.Measurements.OrderBy(x => x.Date).Reverse().First())
                {
                <td>
                    <form method="get" asp-action="Edit" asp-route-id="@meas.ID">
                        <button class="btn-crud-data">Изменить</button>
                    </form>
                </td>
                    <td>
                            <form method="get" asp-action="Delete" asp-route-id="@meas.ID">
                                <button class="btn-crud-data">Удалить</button>
                            </form>
                    </td>
                 }
            </tr>
        }
    </tbody>
</table>

<form method="get" asp-controller="SingleMeasurements" asp-action="Add" asp-route-id="@Model.Muscles">
    <button class="btn-crud-data" method="get" asp-controller="SingleMeasurements" asp-action="Add" asp-route-id="@Model.Muscles">Добавить</button>
</form>

WebTraining/Views/SingleMeasurements/WeightViewMeasurements.cshtml
@using WebTraining.Models.Measurements;
@model WeightMeasViewModel
@{
    ViewData["Title"] = "Значения";
}

<h1>Замеры веса</h1>

<table class="table">
    <thead>
        <tr>
            <th><a>Дата</a></th>
            <th><a>Значение</a></th>
            <th><a>Изменение</a></th>



        </tr>
    </thead>
    <tbody>
        @foreach (var meas in Model.Measurements.OrderBy(x => x.Date).Reverse())
        {
            <tr>
                <td>
                    @Html.DisplayFor(item => meas.Date)
                </td>
                <td align="center">
                    @Html.DisplayFor(item => meas.Value) кг
                </td>
                <td align="center">
                    @if (meas.Change > 0)
                    {
                        <a>+</a>

                        @Html.DisplayFor(item => meas.Change)
                    }
                    else
                    {
                        @Html.DisplayFor(item => meas.Change)
                    }
                </td>


                @if (meas == Model.Measurements.OrderBy(x => x.Date).Reverse().First())
                {
                    <td>
                        <form method="get" asp-action="Edit" asp-route-id="@meas.ID">
                            <button class="btn-crud-data">Изменить</button>
                        </form>
                    </td>
                    <td>
                        <form method="get" asp-action="Delete" asp-route-id="@meas.ID">
                            <button class="btn-crud-data">Удалить</button>
                        </form>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>

<form method="get" asp-controller="SingleMeasurements" asp-action="Add" asp-route-id="@Model.Muscles">
    <button class="btn-crud-data" method="get" asp-controller="SingleMeasurements" asp-action="Add" asp-route-id="@Model.Muscles">Добавить</button>
</form>