WebTraining/Controllers/MeasurementsController/DoubleMeasurementsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebTraining.Core.DTO.MeasurementsDTO;
using WebTraining.Core.Interfaces.IMeasurements;
using WebTraining.DB.Models;
using WebTraining.Models.Measurements;

namespace WebTraining.Controllers.MeasurementsController
{
    [Authorize]
    public class DoubleMeasurementsController : Controller
    {
        private readonly IDoubleMeasurementsService doubleMeasurementsService;
        readonly UserManager<User> userManager;


        public DoubleMeasurementsController(IDoubleMeasurementsService doubleMeasurementsService, UserManager<User> userManager)
        {
            this.doubleMeasurementsService = doubleMeasurementsService;
            this.userManager = userManager;
        }

        public async Task<IActionResult> ShinsViewMeasurements(string type = "Голень")
        {
            User user = await GetUser();
            ShinsMeasViewModel model = new ShinsMeasViewModel()
            {
                Measurements = doubleMeasurementsService.GetNeedMeasurements(user, doubleMeasurementsService.GetTypeOfMuscle(type).ID).ToList()
            };
            return View(model);
        }

        public async Task<IActionResult> ForearmViewMeasurements(string type = "Предплечье")
        {
            User user = await GetUser();
            ForearmMeasViewModel model = new ForearmMeasViewModel()
            {
                Measurements = doubleMeasurementsService.GetNeedMeasurements(user, doubleMeasurementsService.GetTypeOfMuscle(type).ID).ToList()
            };
            return View(model);
        }

        public async Task<IActionResult> LegsViewMeasurements(string type = "Ноги")
        {
            User user = await GetUser();
            LegsMeasViewModel model = new LegsMeasViewModel()
            {
                Measurements = doubleMeasurementsService.GetNeedMeasurements(user, doubleMeasurementsService.GetTypeOfMuscle(type).ID).ToList()
            };
            return View(model);
        }


        public async Task<IActionResult> ViewBitcepsMeasurements(string type="Битцепс")        
        {
            User user = await GetUser();
            BitcepsMeasurementsViewModel model = new BitcepsMeasurementsViewModel()
            {             
                Measurements = doubleMeasurementsService.GetNeedMeasurements(user, doubleMeasurementsService.GetTypeOfMuscle(type).ID).ToList()

            };
            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> Add(string id)
        {
            User user = await GetUser();
            AddDoubleMeasViewModel meas = new AddDoubleMeasViewModel
            {
                Measurementst= new DoubleMeasurementsDTO() 
                {
                    Date = DateTime.Now,
                    UserId = user.Id,
                    MuscleId = doubleMeasurementsService.GetTypeOfMuscle(id).ID
                }
            };
            return View(meas);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddDoubleMeasViewModel meas)
        {
            User user = await GetUser();
            if (ModelState.IsValid)
            {
                doubleMeasurementsService.AddMeasurement(meas.Measurementst, user);
                return RedirectToAction("Index", "Account");
            }
            else
            {
                return View(meas);
            }
        }

        public IActionResult Delete(int id) 
        {
            doubleMeasurementsService.DeleteMeasurement(id);
            return RedirectToAction("Index", "Account");
        }

        [HttpGet]
        public IActionResult Edit(int id) 
        {
            DoubleMeasurementsDTO meas = doubleMeasurementsService.GetMeasurement(id);
            if (meas != null)
            {
                return View(meas);
            }
            return RedirectToAction("Index", "Account");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(DoubleMeasurementsDTO meas) 
        {
            User user = await GetUser();
            if (ModelState.IsValid)
            {
                doubleMeasurementsService.UpdateMeasurement(meas, user);
                return RedirectToAction("Index", "Account");
            }
            return View (meas);
        }

        private async Task<User> GetUser()
        {
            return await userManager.FindByNameAsync(User.Identity.Name);
        }
    }
}

WebTraining/Views/DoubleMeasurements/Add.cshtml
@using WebTraining.Models.Measurements;
@model AddDoubleMeasViewModel
@{
    ViewData["Title"] = "Добавление заметки";
}

<h1>Добавить значение</h1>

<form asp-action="Add" method="post">
    <div class="div-crud-data">
        <label class="label-crud-data" asp-for="Measurementst.LeftValue">Левое значение</label>
        <input class="input-crud-data-exercise" asp-for="Measurementst.LeftValue" type="text" maxlength="6" />
        <span asp-validation-for="Measurementst.LeftValue"></span>
    </div>
    <div class="div-crud-data">
        <label class="label-crud-data" asp-for="Measurementst.RightValue">Правое значение</label>
        <input class="input-crud-data-exercise" asp-for="Measurementst.RightValue" type="text"  maxlength="6"/>
        <span asp-validation-for="Measurementst.RightValue"></span>
    </div>
    <div hidden>
        <label asp-for="Measurementst.Date"></label>
        <input asp-for="Measurementst.Date" type="datetime" />
        <span asp-validation-for="Measurementst.Date"></span>
    </div>
    <div hidden>
        <label asp-for="Measurementst.UserId"></label>
        <input asp-for="Measurementst.UserId" />
        <span asp-validation-for="Measurementst.UserId"></span>
    </div>
    <div hidden>
        <label asp-for="Measurementst.MuscleId"></label>
        <input asp-for="Measurementst.MuscleId" />
        <span asp-validation-for="Measurementst.MuscleId"></span>
    </div>


    <div>
        <input class="btn-add" type="submit" value="Добавить" />
    </div>

</form>

WebTraining/Views/DoubleMeasurements/Edit.cshtml
@model WebTraining.Core.DTO.MeasurementsDTO.DoubleMeasurementsDTO
@{
    ViewData["Title"] = "Редактирование заметки";
}

<h1>Редактировать заметки</h1>

<form method="post" asp-action="Edit">
    <div class="div-crud-data">
        <label class="label-crud-data" asp-for="LeftValue">Левое значение</label>
        <input class="input-crud-data-exercise" asp-for="LeftValue" type="text" maxlength="6" />
        <span asp-validation-for="LeftValue"></span>
    </div>
    <div class="div-crud-data">
        <label class="label-crud-data" asp-for="RightValue">Правое значение</label>
        <input class="input-crud-data-exercise" asp-for="RightValue" type="text" maxlength="6" />
        <span asp-validation-for="RightValue"></span>
    </div>

    <div hidden>
        <label asp-for="Date"></label>
        <input asp-for="Date" type="datetime" />
        <span asp-validation-for="Date"></span>
    </div>
    <div hidden>
        <label asp-for="UserId"></label>
        <input asp-for="UserId" />
        <span asp-validation-for="UserId"></span>
    </div>
    <div hidden>
        <label asp-for="MuscleId"></label>
        <input asp-for="MuscleId" />
        <span asp-validation-for="MuscleId"></span>
    </div>
    <div>
        <input class="btn-add" type="submit" value="Изменить" />
    </div>
</form>

WebTraining/Views/DoubleMeasurements/ForearmViewMeasurements.cshtml
@using WebTraining.Models.Measurements;
@model ForearmMeasViewModel
@{
    ViewData["Title"] = "Значения";
}

<h1>Замеры предплечья</h1>

<table class="table">
    <thead>
        <tr>
            <th><a>Дата</a></th>
            <th><a>Значение левой руки</a></th>
            <th><a>Значение правой руки</a></th>
            <th><a>Изменение левой руки</a></th>
            <th><a>Изменение левой руки</a></th>


        </tr>
    </thead>
    <tbody>
        @foreach (var meas in Model.Measurements.OrderBy(x => x.Date).Reverse())
        {
            <tr>
                <td>
                    @Html.DisplayFor(item => meas.Date)
                </td>
                <td align="center">
                    @Html.DisplayFor(item => meas.LeftValue) см
                </td>
                <td align="center">
                    @Html.DisplayFor(item => meas.RightValue) см
                </td>
                <td align="center">
                    @if (meas.LeftChange > 0)
                    {
                        <a>+</a>

                        @Html.DisplayFor(item => meas.LeftChange)
                    }
                    else
                    {
                        @Html.DisplayFor(item => meas.LeftChange)
                    }
                </td>
                <td align="center">
                    @if (meas.RightChange > 0)
                    {
                        <a>+</a>

                        @Html.DisplayFor(item => meas.RightChange)
                    }
                    else
                    {
                        @Html.DisplayFor(item => meas.RightChange)
                    }

                </td>


                @if (meas == Model.Measurements.OrderBy(x => x.Date).Reverse().First())
                {
                <td>
                    <form method="get" asp-action="Edit" asp-route-id="@meas.ID">
                        <button class="btn-crud-data">Изменить</button>
                    </form>
                </td>
                    <td>
                            <form method="get" asp-action="Delete" asp-route-id="@meas.ID">
                                <button class="btn-crud-data">Удалить</button>
                            </form>
                    </td>
                 }
            </tr>
        }
    </tbody>
</table>

<form method="get"  asp-controller="DoubleMeasurements" asp-action="Add" asp-route-id="@Model.Muscles">
    <button method="get" class="btn-crud-data" asp-controller="DoubleMeasurements" asp-action="Add" asp-route-id="@Model.Muscles">Добавить</button>
</form>

WebTraining/Views/DoubleMeasurements/LegsViewMeasurements.cshtml
@using WebTraining.Models.Measurements;
@model LegsMeasViewModel
@{
    ViewData["Title"] = "Значения";
}

<h1>Замеры ног</h1>

<table class="table">
    <thead>
        <tr>
            <th><a>Дата</a></th>
            <th><a>Значение левой ноги</a></th>
            <th><a>Значение правой ноги</a></th>
            <th><a>Изменение левой ноги</a></th>
            <th><a>Изменение левой ноги</a></th>


        </tr>
    </thead>
    <tbody>
        @foreach (var meas in Model.Measurements.OrderBy(x => x.Date).Reverse())
        {
            <tr>
                <td>
                    @Html.DisplayFor(item => meas.Date)
                </td>
                <td align="center">
                    @Html.DisplayFor(item => meas.LeftValue) см
                </td>
                <td align="center">
                    @Html.DisplayFor(item => meas.RightValue) см
                </td>
                <td align="center">
                    @if (meas.LeftChange > 0)
                    {
                        <a>+</a>

                        @Html.DisplayFor(item => meas.LeftChange)
                    }
                    else
                    {
                        @Html.DisplayFor(item => meas.LeftChange)
                    }
                </td>
                <td align="center">
                    @if (meas.RightChange > 0)
                    {
                        <a>+</a>

                        @Html.DisplayFor(item => meas.RightChange)
                    }
                    else
                    {
                        @Html.DisplayFor(item => meas.RightChange)
                    }

                </td>


                @if (meas == Model.Measurements.OrderBy(x => x.Date).Reverse().First())
                {
                <td>
                    <form method="get" asp-action="Edit" asp-route-id="@meas.ID">
                        <button class="btn-crud-data">Изменить</button>
                    </form>
                </td>
                    <td>
                            <form method="get" asp-action="Delete" asp-route-id="@meas.ID">
                                <button class="btn-crud-data">Удалить</button>
                            </form>
                    </td>
                 }
            </tr>
        }
    </tbody>
</table>

<form method="get" asp-controller="DoubleMeasurements" asp-action="Add" asp-route-id="@Model.Muscles">
    <button method="get" class="btn-crud-data" asp-controller="DoubleMeasurements" asp-action="Add" asp-route-id="@Model.Muscles">Добавить</button>
</form>

WebTraining/Views/DoubleMeasurements/ShinsViewMeasurements.cshtml
@using WebTraining.Models.Measurements;
@model ShinsMeasViewModel
@{
    ViewData["Title"] = "Значения";
}

<h1>Замеры битцепса</h1>

<table class="table">
    <thead>
        <tr>
            <th><a>Дата</a></th>
            <th><a>Значение левой руки</a></th>
            <th><a>Значение правой руки</a></th>
            <th><a>Изменение левой руки</a></th>
            <th><a>Изменение левой руки</a></th>


        </tr>
    </thead>
    <tbody>
        @foreach (var meas in Model.Measurements.OrderBy(x => x.Date).Reverse())
        {
            <tr>
                <td>
                    @Html.DisplayFor(item => meas.Date)
                </td>
                <td align="center">
                    @Html.DisplayFor(item => meas.LeftValue) см
                </td>
                <td align="center">
                    @Html.DisplayFor(item => meas.RightValue) см
                </td>
                <td align="center">
                    @if (meas.LeftChange > 0)
                    {
                        <a>+</a>

                        @Html.DisplayFor(item => meas.LeftChange)
                    }
                    else
                    {
                        @Html.DisplayFor(item => meas.LeftChange)
                    }
                </td>
                <td align="center">
                    @if (meas.RightChange > 0)
                    {
                        <a>+</a>

                        @Html.DisplayFor(item => meas.RightChange)
                    }
                    else
                    {
                        @Html.DisplayFor(item => meas.RightChange)
                    }

                </td>


                @if (meas == Model.Measurements.OrderBy(x => x.Date).Reverse().First())
                {
                    <td>
                        <form method="get" asp-action="Edit" asp-route-id="@meas.ID">
                            <button class="btn-crud-data">Изменить</button>
                        </form>
                    </td>
                    <td>
                        <form method="get" asp-action="Delete" asp-route-id="@meas.ID">
                            <button class="btn-crud-data">Удалить</button>
                        </form>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>

<form method="get" asp-controller="DoubleMeasurements" asp-action="Add" asp-route-id="@Model.Muscles">
    <button method="get" class="btn-crud-data" asp-controller="DoubleMeasurements" asp-action="Add" asp-route-id="@Model.Muscles">Добавить</button>
</form>

WebTraining/Views/DoubleMeasurements/ViewBitcepsMeasurements.cshtml
@using WebTraining.Models.Measurements;
@model BitcepsMeasurementsViewModel
@{
    ViewData["Title"] = "Значения";
}

<h1>Замеры бицепса</h1>

<table class="table">
    <thead>
        <tr>
            <th><a>Дата</a></th>
            <th><a>Значение левой руки</a></th>
            <th><a>Значение правой руки</a></th>
            <th><a>Изменение левой руки</a></th>
            <th><a>Изменение левой руки</a></th>


        </tr>
    </thead>
    <tbody>
        @foreach (var meas in Model.Measurements.OrderBy(x => x.Date).Reverse())
        {
            <tr>
                <td>
                    @Html.DisplayFor(item => meas.Date)
                </td>
                <td align="center">
                    @Html.DisplayFor(item => meas.LeftValue) см
                </td>
                <td align="center">
                    @Html.DisplayFor(item => meas.RightValue) см
                </td>
                <td align="center">
                    @if (meas.LeftChange > 0)
                    {
                        <a>+</a>

                        @Html.DisplayFor(item => meas.LeftChange)
                    }
                    else
                    {
                        @Html.DisplayFor(item => meas.LeftChange)
                    }
                </td>
                <td align="center">
                    @if (meas.RightChange > 0)
                    {
                        <a>+</a>

                        @Html.DisplayFor(item => meas.RightChange)
                    }
                    else
                    {
                        @Html.DisplayFor(item => meas.RightChange)
                    }

                </td>


                @if (meas == Model.Measurements.OrderBy(x => x.Date).Reverse().First())
                {
                <td>
                    <form method="get" asp-action="Edit" asp-route-id="@meas.ID">
                        <button class="btn-crud-data">Изменить</button>
                    </form>
                </td>
                    <td>
                            <form method="get" asp-action="Delete" asp-route-id="@meas.ID">
                                <button class="btn-crud-data">Удалить</button>
                            </form>
                    </td>
                 }
            </tr>
        }
    </tbody>
</table>

<form method="get" asp-controller="DoubleMeasurements" asp-action="Add" asp-route-id="@Model.Muscles">
    <button class="btn-crud-data" method="get" asp-controller="DoubleMeasurements" asp-action="Add" asp-route-id="@Model.Muscles">Добавить</button>
</form>