WebTraining/Controllers/ExerciseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebTraining.Core.DTO;
using WebTraining.Core.Interfaces;
using WebTraining.Core.Models;
using WebTraining.Models;


namespace WebTraining.Controllers
{
    [Authorize]
    public class ExerciseController : Controller
    {
        readonly IExerciseService exerciseService;
        readonly IWebHostEnvironment _appEnvironment;

        public ExerciseController(IExerciseService serv, IWebHostEnvironment appEnvironment)
        {
            exerciseService = serv;
            _appEnvironment = appEnvironment;
        }

        public IActionResult Index()
        {
            ExerciseViewModel viewModel = new ExerciseViewModel()
            {
                Exercises = exerciseService.GetExercises().ToList(),
                Image = exerciseService.GetImages().ToList()
            };
            return View(viewModel);
        }

        public IActionResult Exercise(int id)
        {
            ExerciseEViewModel model = new ExerciseEViewModel
            {
                Exercise = exerciseService.GetExercise(id),
                Image = exerciseService.GetImageExercises(exerciseService.GetExercise(id)).ToList()
            };
            return View(model);
        }


        [HttpGet]
        [Authorize(Roles = "coach, admin")]
        public IActionResult CreateExercise()
        {
            AddEditExerciseViewModel exercise = new AddEditExerciseViewModel
            {
                TypeOfMysc = new TypeOfMyscList(exerciseService.GetTypeOfMuscles().ToList()),
                ExerciseDTO = new ExerciseDTO() { }
            };
            return View(exercise);
        }

        [HttpPost]
        [Authorize(Roles = "coach, admin")]
        public async Task<IActionResult> CreateExercise(AddEditExerciseViewModel exercise, IFormFileCollection uploadedNameImage)
        {
            if (ModelState.IsValid)
            {
                if (uploadedNameImage.Count == 3)
                {
                    exerciseService.AddExercise(exercise.ExerciseDTO);
                    await AddImage(exercise.ExerciseDTO, uploadedNameImage);
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("ImageExercise", "Не хватает картинки. Должно быть загружено 3 картинки");
            }
            exercise.TypeOfMysc = new TypeOfMyscList(exerciseService.GetTypeOfMuscles().ToList());
            return View(exercise);

        }
        [HttpGet]
        [Authorize(Roles = "coach, admin")]

        public IActionResult Delete(int id)
        {
            ExerciseDTO exercise = exerciseService.GetExercise(id);
            if (exercise != null)
            {
                DeletePicture(exercise);
                exerciseService.DeleteExercise(id);
                return RedirectToAction("Index");
            }            
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "coach, admin")]
        public IActionResult EditExercise(int id)
        {
            var exercise = exerciseService.GetExercise(id);
            if (exercise != null)
            {
                AddEditExerciseViewModel model = new AddEditExerciseViewModel
                {
                    ImageExercise = exerciseService.GetImageExercises(exercise).ToList(),
                    TypeOfMysc = new TypeOfMyscList(exerciseService.GetTypeOfMuscles().ToList()),
                    ExerciseDTO = exercise
                };
                return View(model);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize(Roles = "coach, admin")]
        public async Task<IActionResult> EditExerciseAsync(AddEditExerciseViewModel exercise, IFormFile? uploadedNameImage1, IFormFile? uploadedNameImage2, IFormFile? uploadedNameImage3)
        {
            if (ModelState.IsValid)
            {
                exercise.ImageExercise = exerciseService.GetImageExercises(exercise.ExerciseDTO);
                exerciseService.UpdateExercise(exercise.ExerciseDTO);
                await EditImageAsync(exercise.ExerciseDTO, uploadedNameImage1, uploadedNameImage2, uploadedNameImage3);
                return RedirectToAction("Index");
            }
            else
            {
                exercise.TypeOfMysc = new TypeOfMyscList(exerciseService.GetTypeOfMuscles().ToList());
                return View(exercise);
            }
        }

        private async Task EditImageAsync(ExerciseDTO exercise, IFormFile uploadedNameImage1, IFormFile uploadedNameImage2, IFormFile uploadedNameImage3)
        {
            List<ImageExerciseDTO> image = new List<ImageExerciseDTO>(3);
            image.AddRange(exerciseService.GetImageExercises(exercise));
            if (uploadedNameImage1 != null)
            {
                string path = "/Files/" + uploadedNameImage1.FileName;
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedNameImage1.CopyToAsync(fileStream);
                }
                if (image[0]!=null)
                {
                    image[0].PathImage= path;
                    image[0].NameImage= uploadedNameImage1.FileName;
                    exerciseService.UpdatePicture(image[0]);
                }
                else
                {
                    ImageExerciseDTO newimage = new ImageExerciseDTO()
                    {
                        PathImage = path,
                        ExerciseID = exercise.ID,
                        NameImage = uploadedNameImage1.FileName
                    };
                    exerciseService.AddPicture(newimage);
                }
            }
            if (uploadedNameImage2 != null)
            {
                string path = "/Files/" + uploadedNameImage2.FileName;
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedNameImage2.CopyToAsync(fileStream);
                }
                if (image[1] != null)
                {

                    image[1].PathImage = path;
                    image[1].NameImage = uploadedNameImage2.FileName;
                    exerciseService.UpdatePicture(image[1]);
                }
                else
                {
                    ImageExerciseDTO newimage = new ImageExerciseDTO()
                    {
                        PathImage = path,
                        ExerciseID = exercise.ID,
                        NameImage = uploadedNameImage2.FileName
                    };
                    exerciseService.AddPicture(newimage);
                }
            }
            if (uploadedNameImage3 != null)
            {
                string path = "/Files/" + uploadedNameImage3.FileName;
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedNameImage3.CopyToAsync(fileStream);
                }
                if (image.Count==3)
                {
                    image[2].PathImage = path;
                    image[2].NameImage = uploadedNameImage3.FileName;
                    exerciseService.UpdatePicture(image[2]);
                }
                else
                {
                    ImageExerciseDTO newimage = new ImageExerciseDTO()
                    {
                        PathImage = path,
                        ExerciseID = exercise.ID,
                        NameImage = uploadedNameImage3.FileName
                    };
                    exerciseService.AddPicture(newimage);
                }
            }
        }

        private async Task AddImage(ExerciseDTO exercise, IFormFileCollection uploadedNameImage)
        {
            foreach (var item in uploadedNameImage)
            {
                string path = "/Files/" + item.FileName;
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await item.CopyToAsync(fileStream);
                }
                ImageExerciseDTO newimage = new ImageExerciseDTO()
                {
                    ExerciseID = exerciseService.GetExercises().Last().ID,
                    PathImage = path,
                    NameImage = item.FileName
                };
                exerciseService.AddPicture(newimage);
            }
        }

        private void DeletePicture(ExerciseDTO exercise)
        {
            var image = exerciseService.GetImageExercises(exercise);

            foreach (var item in image)
            {
                item.PathImage = _appEnvironment.WebRootPath + item.PathImage;
                if (item.PathImage != _appEnvironment.WebRootPath)
                {
                    System.IO.File.Delete(item.PathImage);
                    exerciseService.DeleteImage(item.ID);
                }
            }
        }
    }
}

WebTraining/Controllers/NotedpadController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebTraining.Core.DTO;
using WebTraining.Core.Interfaces;
using WebTraining.DB.Models;
using WebTraining.Models;

namespace WebTraining.Controllers
{
    [Authorize]
    public class NotedpadController : Controller
    {
        readonly INotepadService notepadService;
        readonly UserManager<User> userManager;

        public NotedpadController(INotepadService serv, UserManager<User> userManager)
        {
            notepadService = serv;
            this.userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            User user = await GetUser();
            IEnumerable<NotepadDTO> notes=notepadService.GetUserNotes(user).ToList();
            NoteViewModel noteView = new NoteViewModel()
            {
                Exercises = notes
            };
            return View(noteView);
        }

        [HttpGet]
        public IActionResult DeleteNote(int id) 
        {
            notepadService.DeleteNote(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> CreateNote()
        {
            User user = await GetUser();
            NotepadDTO note = new NotepadDTO
            {
                UserId = user.Id,
            };
            return View(note);
        }

        [HttpPost]
        public IActionResult CreateNote(NotepadDTO note)
        {
            if (ModelState.IsValid)
            {
                notepadService.AddNote(note);
                return RedirectToAction("Index");
            }
            else
            {
                return View(note);
            }
        }

        [HttpGet]
        public IActionResult EditNote(int id) 
        {
            NotepadDTO note = notepadService.GetNote(id);
            if (note!=null)
            {
                return View(note);
            }
            return RedirectToAction("Index");            
        }

        [HttpPost]
        public IActionResult EditNote(NotepadDTO note)
        {
            notepadService.UpdateNote(note);
            return RedirectToAction("Index");
        }

        private async Task<User> GetUser()
        {
            return await userManager.FindByNameAsync(User.Identity.Name);
        }
    }
}

WebTraining/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebTraining.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid site-header">                
                <a class="navbar-brand " asp-area="" asp-controller="Home" asp-action="Index" >
                    <img src="~/files/image/siteimage/training.png" height="60px" alt="training.png"/> WebTraining</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark header-text" asp-area="" asp-controller="Exercise" asp-action="Index">Упражнения</a>
                            </li>
                            @if (User.IsInRole("coach") | User.IsInRole("admin"))
                            {
                            <li class="nav-item">
                                    <a class="nav-link text-dark header-text" asp-controller="Training" asp-action="AllTraining">Тренировки</a>
                            </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark header-text" asp-controller="Training" asp-action="Index">Тренировки</a>
                                </li>
                            }
                            <a class="nav-link text-dark header-text" asp-area="" asp-controller="Notedpad" asp-action="Index">Блокнот</a>
                        }              
                    </ul>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a class="nav-link text-dark" asp-controller="Account" asp-action="Index">@User.Identity.Name</a>
                        }
                        else
                        {
                            <a style="margin-right:10px; font-size:20px" asp-controller="Account" asp-action="Login">Вход</a>
                            <a style="margin-right:10px; font-size:20px" asp-controller="Account" asp-action="Register">Регистрация</a>
                        }
                </div>
            </div>
        </nav>
    </header>
    <div style="margin-bottom: 50px" class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer  class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebTraining
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>